# Reference copy of the block that install.ps1 writes into $PROFILE.
# Keep it in sync with Get-ProfileBlock inside install.ps1.
#
# Both PowerShell 5.1 (Documents\WindowsPowerShell) and PowerShell 7
# (Documents\PowerShell) get this block, so the setup works in either shell.

# >>> powershell-setup:managed-block >>>
# Generated by install.ps1 - edits inside this block are overwritten.

# Oh My Posh prompt
$psuOmp = Get-Command oh-my-posh -ErrorAction SilentlyContinue
if ($psuOmp) {
    try {
        if ([Console]::OutputEncoding.WebName -ne 'utf-8') { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 }
        $psuThemes = $env:POSH_THEMES_PATH
        if (-not $psuThemes) { $psuThemes = Join-Path $env:LOCALAPPDATA 'Programs\oh-my-posh\themes' }
        $psuConfig = Join-Path $psuThemes 'wopian.omp.json'
        if (Test-Path -LiteralPath $psuConfig) {
            oh-my-posh init pwsh --config $psuConfig | Invoke-Expression
        } else {
            oh-my-posh init pwsh | Invoke-Expression
        }
    } catch {
        Write-Warning ('oh-my-posh: ' + $_.Exception.Message)
    }
}

# Git status in the prompt and file icons everywhere
Import-Module posh-git -ErrorAction SilentlyContinue
Import-Module Terminal-Icons -ErrorAction SilentlyContinue

# PSReadLine
try {
    $psuPsrl = Import-Module PSReadLine -PassThru -ErrorAction Stop
    Set-PSReadLineOption -EditMode Emacs -BellStyle None
    if ($psuPsrl.Version -ge [version]'2.1.0') {
        # needs a console with virtual terminal support - silent when redirected
        Set-PSReadLineOption -PredictionSource History -ErrorAction SilentlyContinue
    }
    Set-PSReadLineKeyHandler -Chord 'Ctrl+d' -Function DeleteChar
} catch { }

# fzf (Ctrl+f file picker, Ctrl+r reverse history)
if ((Get-Command fzf -CommandType Application -ErrorAction SilentlyContinue) -and (Get-Module -ListAvailable -Name PSFzf)) {
    try {
        Import-Module PSFzf -ErrorAction Stop
        Set-PSFzfOption -PSReadlineChordProvider 'Ctrl+f' -PSReadlineChordReverseHistory 'Ctrl+r'
    } catch { }
}

# Aliases
Set-Alias -Name ll -Value ls
Set-Alias -Name grep -Value findstr
if (Get-Command git -ErrorAction SilentlyContinue) { Set-Alias -Name g -Value git }
if (Get-Command nvim -ErrorAction SilentlyContinue) { Set-Alias -Name vim -Value nvim }
$psuGitCmd = Get-Command git -ErrorAction SilentlyContinue
$psuGitRoot = $null
if ($psuGitCmd -and $psuGitCmd.CommandType -eq 'Application') {
    $psuCandidate = Split-Path -Parent (Split-Path -Parent $psuGitCmd.Source)
    if (Test-Path -LiteralPath (Join-Path $psuCandidate 'usr\bin')) { $psuGitRoot = $psuCandidate }
    elseif (Test-Path -LiteralPath 'C:\Program Files\Git\usr\bin') { $psuGitRoot = 'C:\Program Files\Git' }
}
if ($psuGitRoot) {
    $psuTig = Join-Path $psuGitRoot 'usr\bin\tig.exe'
    $psuLess = Join-Path $psuGitRoot 'usr\bin\less.exe'
    if (Test-Path -LiteralPath $psuTig) { Set-Alias -Name tig -Value $psuTig }
    if (Test-Path -LiteralPath $psuLess) { Set-Alias -Name less -Value $psuLess }
}

# Utilities
function which ($command) {
    Get-Command -Name $command -ErrorAction SilentlyContinue |
        Select-Object -ExpandProperty Path -ErrorAction SilentlyContinue
}
# <<< powershell-setup:managed-block <<<
